"""Split the original display font without changing its character coverage.

Run with fonttools[woff]==4.61.1 installed. Generated files are checked in;
normal Next.js builds need neither Python nor fontTools. --check verifies the
generated CSS, character coverage and text metrics without rebuilding fonts.
"""

import argparse
from collections import defaultdict
from io import BytesIO
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / "src" / "fonts"
SOURCE = FONTS / "source-han-sans-cn.woff2"
OUTPUT = FONTS / "source-han-sans-cn"
STYLESHEET = FONTS / "source-han-sans-cn-subsets.css"
FAMILY = "Source Han Sans CN Extended"


def common_codepoints():
    # Latin, punctuation and full-width forms, plus GB2312 level-one Chinese.
    # A stable repertoire keeps URLs unchanged when articles are added.
    points = set(range(0x250))
    points.update(range(0x2000, 0x2070))
    points.update(range(0x3000, 0x3040))
    points.update(range(0xFF00, 0xFFF0))
    for high in range(0xB0, 0xD8):
        for low in range(0xA1, 0xFF):
            try:
                points.add(ord(bytes([high, low]).decode("gb2312")))
            except UnicodeDecodeError:
                pass
    return points


def unicode_range(points):
    runs = []
    for point in sorted(points):
        if runs and point == runs[-1][1] + 1:
            runs[-1][1] = point
        else:
            runs.append([point, point])
    return ",".join(
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
        for start, end in runs
    )


def font_groups(points):
    core = points & common_codepoints()
    extensions = defaultdict(set)
    for point in sorted(points - core):
        # A rare character downloads at most one small Unicode block.
        extensions[point // 512 * 512].add(point)
    return {"core": core} | {
        f"u{start:04x}": values for start, values in sorted(extensions.items())
    }


def stylesheet(groups):
    rules = ["/* Generated by scripts/build-font-subsets.py. Do not edit by hand. */"]
    for name, points in groups.items():
        if name == "core":
            continue  # next/font/local handles the single preloaded core file.
        rules.append(
            f'@font-face {{\n  font-family: "{FAMILY}";\n'
            f'  src: url("./source-han-sans-cn/{name}.woff2") format("woff2");\n'
            "  font-weight: 400;\n  font-style: normal;\n  font-display: swap;\n"
            f"  unicode-range: {unicode_range(points)};\n}}"
        )
    return "\n\n".join(rules) + "\n"


def build(original, groups):
    OUTPUT.mkdir(parents=True, exist_ok=True)
    # Decode WOFF2 transforms once; decoding the complete CJK font per block
    # dominates the time needed to generate small subsets.
    buffer = BytesIO()
    original.flavor = None
    original.save(buffer)
    source_bytes = buffer.getvalue()
    for name, points in groups.items():
        font = TTFont(BytesIO(source_bytes), recalcTimestamp=False)
        options = subset.Options()
        options.layout_features = ["*"]
        options.name_IDs = ["*"]
        options.name_legacy = True
        options.notdef_outline = True
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=points)
        subsetter.subset(font)
        font.flavor = "woff2"
        target = OUTPUT / f"{name}.woff2"
        font.save(target)
        font.close()
        print(f"{name}: {len(points)} codepoints, {target.stat().st_size:,} bytes", flush=True)
    STYLESHEET.write_text(stylesheet(groups), encoding="utf-8")


def verify(original, groups):
    original_cmap = original.getBestCmap()
    seen = set()
    for name, points in groups.items():
        with TTFont(OUTPUT / f"{name}.woff2") as font:
            cmap = font.getBestCmap()
            assert set(cmap) == points, f"Character coverage changed in {name}"
            assert not seen & points, f"Overlapping character coverage in {name}"
            seen.update(points)
            assert font["head"].unitsPerEm == original["head"].unitsPerEm
            for metric in ("ascent", "descent", "lineGap"):
                assert getattr(font["hhea"], metric) == getattr(original["hhea"], metric)
            for point, glyph in cmap.items():
                assert font["hmtx"][glyph] == original["hmtx"][original_cmap[point]], (
                    f"Text metrics changed for U+{point:X}"
                )
    assert seen == set(original_cmap), "Some original characters are missing"
    assert STYLESHEET.read_text(encoding="utf-8") == stylesheet(groups)
    core_size = (OUTPUT / "core.woff2").stat().st_size
    print(
        f"Verified {len(seen):,} codepoints in {len(groups)} files; "
        f"core {core_size:,} bytes vs original {SOURCE.stat().st_size:,} bytes.",
        flush=True,
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    with TTFont(SOURCE, recalcTimestamp=False) as original:
        groups = font_groups(set(original.getBestCmap()))
        if not args.check:
            build(original, groups)
        verify(original, groups)
